## Import Libraries

In [1]:
import numpy as np
import pandas as pd

## Import Dataset

In [8]:
df = pd.read_excel('Swap and Swaption Markets.xlsx', sheet_name=None)

In [19]:
sheets = list(df.keys())
sheets

['LIBOR (legacy)', 'OIS (SOFR)', 'OIS (Term SOFR)', 'Swaption']

In [24]:
df_LIBOR = df[sheets[0]].copy()
df_LIBOR;

Notes on LIBOR Rates on first inspection:
* Day Count Convention: 30/360
* Floating Rate: LIBOR 6M
* Floating Leg Frequency and Fixed Leg Frequency: Semi-Annual

In [26]:
df_LIBOR = df_LIBOR.dropna(axis=1)
df_LIBOR

   Tenor Product    Rate
0     6m   LIBOR  0.0450
1     1y     IRS  0.0480
2     2y     IRS  0.0500
3     3y     IRS  0.0515
4     4y     IRS  0.0525
5     5y     IRS  0.0530
6     7y     IRS  0.0550
7    10y     IRS  0.0570
8    15y     IRS  0.0600
9    20y     IRS  0.0650
10   30y     IRS  0.0700

In [27]:
df[sheets[1]].copy()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,NaN,NaN,NaN,Day Count Convention,30/360
1,NaN,NaN,NaN,NaN,Floating Rate,SOFR 1D
2,NaN,NaN,NaN,NaN,O/N Leg Frequency,Annual
3,NaN,NaN,NaN,NaN,Fixed Leg Frequency,Annual

## Part 1: Bootstrapping Swap Curves

### A: LIBOR Bootstrapped Discount Factor